### ISSUE TITLE
Show server endpoint errors

### ISSUE THREAD

**Issue by paulrobertlloyd** [benjifs/sparkles#12]
If an error is encountered, Sparkles shows a message saying ‘An unexpected error has occurred’. However, an endpoint may return an error message, which can be used to help a user fix the error.

For example, if I try to post a movie post, I get an error. Looking at my logs, I can see this is because `No configuration provided for watch post type`. For Indiekit, the error is returned in a JSON response (https://github.com/getindiekit/indiekit/blob/b5259716be540f2936034d5ddc6e5c673b094fda/packages/indiekit/lib/middleware/error.js#L41-L48).

Whether it be returning the full error response, or any `error` and/or `error_description` value returned from a Micropub server, that would help diagnose issues.

**Comment by benjifs** [comment]
Hopefully should be fixed. I wasn't sending an `accept` header from the proxy function so it was receiving html instead of JSON and wouldn't display anything because it couldn't parse it.

**Comment by paulrobertlloyd** [comment]
Perfect, all fixed! 👍
