### ISSUE TITLE
Documentation on how to test locally

### ISSUE THREAD

**Issue by paulrobertlloyd** [benjifs/sparkles#18]
I can run the application locally using `netlify dev`, but I can’t authenticate using a third-party IndieAuth endpoint. Right now I’m deploying to Netlify and using `console.log` to debug changes, which is time consuming and error prone.

Is there a way to test locally, perhaps by providing a placeholder session token (one that could be edited to test different scenarios)? How do you test your changes locally @benjifs?

**Comment by benjifs** [comment]
I'm working on some new features that are almost ready to go but wanted to add some dev and docs related improvements as well. I'm testing out this screen that will only show when running in dev and wanted to get your thoughts:

![Screenshot 2023-12-07 at 12 09 12 PM](https://github.com/benjifs/sparkles/assets/4167938/084e39de-3ece-4958-bf84-59fe8bcf55ad)

That way you can open the details tag and enter your own micropub endpoint and access token. Is that sort of what you were thinking?

**Comment by paulrobertlloyd** [comment]
Yes, I think that’d be perfect! Let know when it’s ready to test.

**Comment by benjifs** [comment]
I just added the changes from my branch. Its fairly minor and I added some minor styling things as well but if you wanted to check it out, its here: https://github.com/benjifs/sparkles/tree/feat/dev-docs

Any recommendations you have, let me know.

**Comment by paulrobertlloyd** [comment]
Works perfectly! Well, almost. Just a few tiny snags:

- The settings screen is not available.
- The ‘Logged in as’ text doesn’t show the URL posts will be published to:

  <img width="220" alt="Screenshot 2023-12-12 at 11 58 10" src="https://github.com/benjifs/sparkles/assets/813383/937ebab6-a67f-49fa-a58e-a3bbb90dd3c6">

However, I can publish posts, so the destination URL is available to Sparkles.

I’m guessing both of these depend on having the URL you signed in with? In the case of using an access token however, I believe it should include a `me` value that would be the destination URL it gives permission to publish to. Maybe in dev mode, that value could be used instead?

**Comment by benjifs** [comment]
Awesome! Fixed the redirect and if the `me` value isn't entered, it'll default to the value entered for the micropub endpoint. I also made a quick change so it shows "**[DEV]**" before "Logged in as" as a visual indicator to remind someone whether they logged in the normal way or the manual way.

**Comment by benjifs** [comment]
Took a minute but just merged these changes into the main branch (#21). I'll close this issue now but happy to add more things that will be helpful for testing in the future
