### ISSUE TITLE
media-endpoint not found

### ISSUE THREAD

**Issue by paulrobertlloyd** [benjifs/sparkles#3]
I love Sparkles ✨ Such a brilliantly simple Micropub interface.

I tried using it with my own website however, and am getting the error `media-endpoint not found` when clicking on the image post type.

I have a media endpoint configured, which is advertised when visiting `https://kit.paulrobertlloyd.com/micropub?q=config`. It returns a number of values, including the following:

```jsonc
{
  …
  "media-endpoint": "https://kit.paulrobertlloyd.com/media",
  …
}
```

This works with other clients. Trying to follow where in the code where this value added to the stored config, and from a cursory look it seems like this should work. This config endpoint is also behind authorisation, if that might cause some issues?

(I’m using [Indiekit](https://github.com/getindiekit/indiekit) for my Micropub server).

**Comment by benjifs** [comment]
> I tried using it with my own website however, and am getting the error `media-endpoint not found` when clicking on the image post type.

I'm testing with a local version of indiekit and I am also seeing this issue.

There may be something I'm assuming incorrectly from the [spec](https://micropub.spec.indieweb.org/#configuration) so just wanted to clarify whats happening on my end.

- After the URL is entered, the authentication and micropub endpoints are found during [discovery](https://indieauth.spec.indieweb.org/#discovery-by-clients).
- After authentication, I'm saving the `access_token` received from the `token_endpoint` (see: [Example 12](https://indieauth.spec.indieweb.org/#example-12)).
- With the `access_token` and `micropub-endpoint`, do a discovery GET request:
```
// From: https://micropub.spec.indieweb.org/#discovery
GET /micropub?q=config
Authorization: Bearer xxxxxxxxx
{
  "media-endpoint": "https://media.example.com/micropub"
}
```

What I'm seeing is that when making that request, I see a 302 to `/session/login` which ends in a 200 response and the indiekit micropub landing page. I've tried this from the client and `curl` and see the same.

Is this what indiekit is expecting or am I using the wrong token or endpoint here?

---

> I was experimenting with this as well and I think it could be because sparkles expects \<media-endpoint\>?q=config to return successfully. I don't think this is part of the spec.

I was trying to find a source for this proposed spec and came up with nothing. Not sure where I got this from. The intent of `/media-endpoint?q=config` as it works in mine is that it returns a list of supported properties. In my case:
```
{ "q": [ "source" ] }
```
Which then calls `/media-endpoint?q=source` as discussed in /indieweb/micropub-extensions#14. This is meant to get the latest images uploaded to the media endpoint and show them in a gallery like view.

If I dont find a source for `q=config` in this context, I'll remove it and do a direct call to `q=source` and if neither are found, provide a more descriptive error with a link to the discussion from above.

**Comment by paulrobertlloyd** [comment]
> Is this what indiekit is expecting or am I using the wrong token or endpoint here?

At first blush it all looks correct. However, I’m still seeing the same issue with the latest updates, and in fact, attempting to post from Sparkles I get an error: ‘An unexpected error occurred’.

When I look at the server logs, the request gets though, using a valid Bearer token. I also see the request to get the config being redirected to `/session/login?redirect=/micropub?q=config`.

More investigation needed.

* * *

As to Micropub extension queries, Indiekit supports the vast majority of the proposals (see this [support checklist](https://getindiekit.com/specifications#micropub)), but you are correct, there is no `config` query for the Media endpoint.

**Comment by paulrobertlloyd** [comment]
FWIW, in the Micropub query request, the header shows `content-type` as `undefined`, wonder if that might be causing some issues?

```js
// /micropub?q=config
headers: {
﻿  host: 'indiekit.up.railway.app',
﻿  accept: '*/*',
﻿  'accept-encoding': 'gzip, deflate, br',
﻿  authorization: 'Bearer [REDACTED]',
  ﻿'content-type': 'undefined',
﻿  'user-agent': 'node-fetch',
  ﻿'x-forwarded-for': '3.234.144.21',
﻿  'x-forwarded-proto': 'https',
﻿  'x-envoy-external-address': '3.234.144.21',
﻿  'x-request-id': 'cfdc235d-d932-435d-91c6-df9106ad748c'
﻿}
```

**Comment by benjifs** [comment]
I'm trying a few more things out and running into dead ends here. I want to walk through what I'm doing so maybe we can figure out where I'm going wrong:
* Login to indiekit enabled site works
* `micropub?q=config` redirects to `/auth/token`
* Test on postman and curl and see the following error:
```
{
    "error": "not_implemented",
    "error_description": "This feature requires a database",
    "stack": "NotImplementedError: This feature requires a database\n    at IndiekitError.notImplemented (file:///root/kit/node_modules/@indiekit/error/index.js:28:12)\n    at queryController,
    ...
}
```
* Outside of sparkles, I'm also just logging in directly to indiekit and grabbing the **Access Token** from there to test the above but I'm seeing the same results.
* If I login to [micropublish](https://micropublish.net/) while running my indiekit server with `--debug`, I also see the redirect happening right after login but before it shows the post options.

I tried with and without a local mongodb but I still see the same. Should the db be configured somewhere outside of the `.env` file?

I tried setting the `content-type` header just in case but I'm still seeing the same thing while testing.

**Comment by paulrobertlloyd** [comment]
Looking at this again, and trying to post a note, notice that the bearer token Sparkles uses has a `me` value that is that of the Indiekit Micropub server, not the website URL.

For example, if I enter `https://indiekit-sandbox.netlify.app` as my website, Sparkles will go on to create a bearer token that has a `me` value of `https://indiekit.up.railway.app/`. That means that Indiekit will reject the token when it comes to authenticating any subsequent request.

I think this might be the offending code: https://github.com/benjifs/sparkles/blob/5b09513efd9c33eb88076286454e9e5f982a107d/src/js/Pages/LoginPage.js#L34

Not quite sure why `me` defaults to `issuer` or `url`, it should probably be just `url`, no?

(Sidenote: the `"This feature requires a database"` error should no longer present itself using Indiekit v1.0.0-beta.3)

**Comment by benjifs** [comment]
Sorry for the delay getting back to this. Thanks for the handling the "database" error for indiekit. It was easier to setup and see what the issue was this time around.

I just made that change and completely agree with you. Not sure what my original intent for using `issuer` and defaulting to `url` but it definitely makes sense here that `me` is always `url`.

In my case, I have `issuer` setup coincidentally to match `me` which is probably why this has worked for me.

Let me know if you get a chance to try it out and if you see any improvements now.

**Comment by paulrobertlloyd** [comment]
Sparkles can now find my media endpoint, and show previously uploaded media. However, I still can’t upload media, but will open a separate issue to track that issue.
